@echo off
echo Starting DTL API...
start "DTL API" cmd /k "cd dtlapi && dotnet run"

echo Waiting for API to start...
timeout /t 5 /nobreak > nul

echo Starting React App...
start "React App" cmd /k "cd dtlmgr && npm start"

echo Both applications are starting...
echo API: http://localhost:5272
echo React App: http://localhost:3000
echo Press any key to exit...
pause > nul
